@startuml
title 任务调度模块流程

start

:接收任务请求;

if (任务类型?) then (入库)

  if (是否已扫码绑定?) then (是)
    :使用已有容器-物料绑定;
  else (否)
    :分配空容器;
    :分配空库位;
    :建立容器-物料-库位绑定;
  endif

  :下发入库任务;
  :更新任务状态 RUNNING;
  :执行完成;
  :更新状态 FINISHED;

else (出库)

  :根据任务定位容器与库位;
  :下发出库任务;
  :更新任务状态 RUNNING;
  :执行完成;

  if (是否扫码解绑?) then (是)
    :扫码容器;
    :解除容器与物料绑定;
  else (否)
    :自动解除绑定;
  endif

  :更新任务状态 FINISHED;

endif

stop
@enduml